
spring:
  application:
    name: mscartoes
  rabbitmq:
    host: ${RABBITMQ_SERVER}
    port: 5672
    username: guest
    password: guest

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka-user:eureka-user@${EUREKA_SERVER}:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

mq:
  queues:
    emissao-cartoes: emissao-cartoes